### ISSUE TITLE
mtc.model error meesage

### ISSUE THREAD

**Issue by sarizwan1986** [MathiasHarrer/Doing-Meta-Analysis-in-R#11]
While trying to run this part of the code: 
```
model <- mtc.model(network, 
                   linearModel = "random",
                   n.chain = 4)
```
The output shown is
Error in mtc.model(network, linearModel = "random", n.chain = 4, likelihood = NULL,  :  No appropriate likelihood could be inferred. Please specify one.

If I specify normal and identity for the likelihood and link the error changes to 

Error in validate.data.normal.identity(list(study = c(1L, 1L, 2L, 2L,  :  all(data.ab[["std.err"]] > 0) is not TRUE

On a related note, the Willms1999 study has three entries and the placebo arm has an std.err value of 0.4002. Isn't this supposed to be NA?

P.S The data was loaded from the file load("senn2013_reshape.rda")

**Comment by vangelis357** [comment]
So? What was the problem??

**Comment by vangelis357** [comment]
https://stackoverflow.com/questions/68700943/bayesian-network-meta-analysis-gemtc - THE ANSWER
