### ISSUE TITLE
Typo in 12.1

### ISSUE THREAD

**Issue by austinj** [MathiasHarrer/Doing-Meta-Analysis-in-R#4]
The very last analysis in 12.1, where the model without level 3 is being compared to the full three-level model using `anova()`, reads `anova(full.model, model.l2.removed)` when it should read `anova(full.model, model.l3.removed)`. As written, the code is just repeating the previous anova. [thanks for the great book!]

**Comment by jsstanley** [comment]
I've submitted a pull request to fix this.
