### ISSUE TITLE
cannot open Doing_Meta_Analysis_in_R.pdf  

### ISSUE THREAD

**Issue by Mosen111** [MathiasHarrer/Doing-Meta-Analysis-in-R#6]
Hi. I downloaded the pdf file, but unfortunately, I cannot read it as I get an error saying that the document page tree has an issue. can you please let me know how to solve this? cheers

**Comment by jsstanley** [comment]
I can reproduce this when downloading the pdf provided in the main repo. 

I tried to build the bookdown project into a pdf locally but I am having problems with that too. It might require some tweaks to the code before a pdf can be generated. 

I will report back if I manage to get it working.

**Comment by MjdMahasneh** [comment]
@jsstanley @Mosen111 I tried building the pdf by uploading the Latex related files (e.g. .tex .bbl etc.) into overleaf. The figures too, you would have to move all images into the main directory (same dir of .tex file). It compiled from first run, however, some of the figures are missing, am still trying to find out  where they are. Hope this helps.
